### ISSUE TITLE
Notice: Funkcija payment_method tika izsaukta nepareizi.

### ISSUE THREAD

**Issue by karlisfeldmanis** [klix-app/klix-woocommerce-plugin#2]
WooCommerce versija: 7.0.0
Wordpress versija: 6.0.3

Notice: Funkcija payment_method tika izsaukta nepareizi. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/../page-checkout.php'), apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_received, wc_get_template, include('/themes/../woocommerce/checkout/thankyou.php'), do_action('woocommerce_thankyou'), WP_Hook->do_action, WP_Hook->apply_filters, custom_woocommerce_auto_complete_order, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Lūdzu, apskatiet [WordPress atkļūdošanu](https://wordpress.org/support/article/debugging-in-wordpress/) lai iegūtu vairāk informācijas. (Šis ziņojums tika pievienots 3.0 versijā.) in /Users/karlis.feldmanis/Sites/../wp-includes/functions.php on line 5833

**Comment by karlisfeldmanis** [comment]
Notice fix:

spell-callback-controller.php

Old
if($purchase_id === "" or !in_array($order->payment_method, $payment_gateways)){
    return;
}

New
if($purchase_id === "" or $purchase_id === NULL or !in_array($order->payment_method, $payment_gateways)){
    return;
}

**Comment by karlisfeldmanis** [comment]
also

$order->payment_method to $order->get_payment_method()
$order->status !== "completed" to $order->get_status() !== "completed"

**Comment by JackDev42** [comment]
Thank you for your notice.
We included your notices in our latest release
